# Generated by Django 5.1.6 on 2025-02-11 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0008_alter_fitcrawleruser_gym'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.CharField(max_length=511)),
                ('width', models.IntegerField()),
                ('layout', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='game_stats', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('max_health', models.IntegerField()),
                ('coins', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DungeonExploration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.IntegerField()),
                ('previous_location', models.IntegerField()),
                ('direction', models.CharField(max_length=7)),
                ('health', models.IntegerField()),
                ('exploration_start', models.DateTimeField()),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeon.dungeon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
