# Generated by Django 5.1.6 on 2025-03-02 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_rank', models.IntegerField()),
                ('name', models.CharField(max_length=63)),
                ('defense_factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boots_rank', models.IntegerField()),
                ('name', models.CharField(max_length=63)),
                ('ap_reduction_factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_rank', models.IntegerField()),
                ('name', models.CharField(max_length=63)),
                ('healing_factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sword_rank', models.IntegerField()),
                ('name', models.CharField(max_length=63)),
                ('strength_boost', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='gamestats',
            name='action_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dungeonexploration',
            name='exploration_start',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='armor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dungeon.armor'),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='boots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dungeon.boots'),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_noob_task', models.IntegerField()),
                ('num_easy_task', models.IntegerField()),
                ('num_medium_task', models.IntegerField()),
                ('num_hard_task', models.IntegerField()),
                ('num_expert_task', models.IntegerField()),
                ('total_minutes_walked', models.IntegerField()),
                ('total_water_drank_L', models.FloatField()),
                ('total_fruit_veggie_servings', models.IntegerField()),
                ('reward_action_points', models.IntegerField()),
                ('reward_armor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dungeon.armor')),
                ('reward_boots', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dungeon.boots')),
                ('reward_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dungeon.staff')),
                ('reward_sword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dungeon.sword')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_completed', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeon.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gamestats',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dungeon.staff'),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='sword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dungeon.sword'),
        ),
    ]
