# Generated by Django 5.1.6 on 2025-03-02 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0003_alter_dungeonexploration_exploration_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeonexploration',
            name='exploration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 21, 27, 48, 91109)),
        ),
        migrations.AlterField(
            model_name='milestonelog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 21, 27, 48, 91109)),
        ),
    ]
