# Generated by Django 5.1.6 on 2025-03-09 01:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0004_alter_dungeonexploration_exploration_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestats',
            name='dungeons_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='reward_max_health',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='total_dungeons_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dungeonexploration',
            name='exploration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 20, 7, 43, 465614)),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='action_points',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='coins',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='max_health',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='num_easy_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='num_expert_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='num_hard_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='num_medium_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='num_noob_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='reward_action_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='reward_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dungeon.armor'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='reward_boots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dungeon.boots'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='reward_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dungeon.staff'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='reward_sword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dungeon.sword'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='total_fruit_veggie_servings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='total_minutes_walked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='total_water_drank_L',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='milestonelog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 20, 7, 43, 481351)),
        ),
    ]
