# Generated by Django 5.1.6 on 2025-03-09 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0004_alter_dungeonexploration_exploration_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeonexploration',
            name='exploration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 22, 39, 11, 466435)),
        ),
        migrations.AlterField(
            model_name='milestonelog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 22, 39, 11, 469435)),
        ),
    ]
