# Generated by Django 5.1.6 on 2025-03-09 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0005_gamestats_dungeons_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeonexploration',
            name='exploration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 20, 9, 11, 972301)),
        ),
        migrations.AlterField(
            model_name='milestonelog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 20, 9, 11, 972301)),
        ),
    ]
