# Generated by Django 5.1.6 on 2025-03-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0005_alter_dungeonexploration_exploration_start_and_more'),
        ('dungeon', '0006_alter_dungeonexploration_exploration_start_and_more'),
    ]

    operations = [
    ]
