# Generated by Django 5.1.7 on 2025-03-16 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0007_merge_20250308_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='sprite_path',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='boots',
            name='sprite_path',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='sprite_folder',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='sprite_path',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='sword',
            name='sprite_path',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='dungeonexploration',
            name='exploration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 22, 25, 55, 639372)),
        ),
        migrations.AlterField(
            model_name='milestonelog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 22, 25, 55, 643468)),
        ),
    ]
