# Generated by Django 5.1.7 on 2025-03-16 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0008_armor_sprite_path_boots_sprite_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeonexploration',
            name='exploration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 22, 27, 39, 267228)),
        ),
        migrations.AlterField(
            model_name='milestonelog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 22, 27, 39, 272108)),
        ),
    ]
