# Generated by Django 5.1.7 on 2025-03-17 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0009_alter_dungeonexploration_exploration_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='difficulty_score',
            field=models.CharField(choices=[('Noob', 'Noob'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Expert', 'Expert')], default='Medium', max_length=31),
        ),
        migrations.AlterField(
            model_name='dungeonexploration',
            name='exploration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 0, 43, 42, 657202)),
        ),
        migrations.AlterField(
            model_name='milestonelog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 0, 43, 42, 660119)),
        ),
    ]
