# Generated by Django 5.1.7 on 2025-03-24 22:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0010_dungeon_difficulty_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('strength', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('sprite_path', models.CharField(blank=True, max_length=63, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dungeonexploration',
            name='id',
        ),
        migrations.AddField(
            model_name='dungeon',
            name='boss_monster_spawn',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='chest_spawn',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='common_monster_spawn',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='uncommon_monster_spawn',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='wall_spawn',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='dungeonexploration',
            name='dungeon_layout',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dungeonexploration',
            name='exploration_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dungeonexploration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dungeon_exploration', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='milestonelog',
            name='time_completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='boss_monster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss', to='dungeon.dungeonenemy'),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='common_monster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common', to='dungeon.dungeonenemy'),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='uncommon_monster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uncommon', to='dungeon.dungeonenemy'),
        ),
    ]
