# Generated by Django 5.1.7 on 2025-03-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0011_dungeonenemy_remove_dungeonexploration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeon',
            name='boss_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss', to='dungeon.dungeonenemy'),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='common_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common', to='dungeon.dungeonenemy'),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='uncommon_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uncommon', to='dungeon.dungeonenemy'),
        ),
    ]
