# Generated by Django 5.1.7 on 2025-03-31 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0013_dungeon_difficulty_quantifer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonBattle',
            fields=[
                ('exploration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dungeon_battle', serialize=False, to='dungeon.dungeonexploration')),
                ('enemy_health', models.IntegerField()),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeon.dungeonenemy')),
            ],
        ),
    ]
