# Generated by Django 5.1.7 on 2025-03-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0014_dungeonbattle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeonbattle',
            name='enemy_health',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dungeonexploration',
            name='health',
            field=models.FloatField(),
        ),
    ]
