# Generated by Django 5.1.6 on 2025-02-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_task_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty_score',
            field=models.CharField(choices=[('Noob', 'Noob'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Expert', 'Expert')], default='Medium', max_length=31),
        ),
    ]
