# Generated by Django 5.1.6 on 2025-03-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_dailylog_tasklog_delete_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='time_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='time_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
