# Generated by Django 5.1.6 on 2025-03-09 03:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_alter_dailylog_time_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 22, 39, 11, 457750)),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.task'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 22, 39, 11, 456759)),
        ),
    ]
