# Generated by Django 5.1.6 on 2025-03-09 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_alter_dailylog_time_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 20, 9, 11, 972301)),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 20, 9, 11, 972301)),
        ),
    ]
