# Generated by Django 5.1.6 on 2025-03-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_task_is_completed_alter_dailylog_time_completed_and_more'),
        ('fitness', '0009_alter_dailylog_time_completed_and_more'),
    ]

    operations = [
    ]
