# Generated by Django 5.1.7 on 2025-03-16 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_merge_20250308_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 22, 25, 55, 638195)),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 22, 25, 55, 637746)),
        ),
    ]
