# Generated by Django 5.1.7 on 2025-03-16 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_alter_dailylog_time_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 22, 27, 39, 263947)),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='time_completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 22, 27, 39, 263535)),
        ),
    ]
