# Generated by Django 5.1.7 on 2025-03-24 22:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_alter_dailylog_time_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='time_completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='time_completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
