# Generated by Django 5.1.7 on 2025-04-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_alter_dailylog_time_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
    ]
