# Generated by Django 5.1.7 on 2025-04-01 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0015_remove_task_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='days_of_week',
        ),
    ]
