# Generated by Django 5.1.6 on 2025-02-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercisevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisevideo',
            name='video_link',
            field=models.URLField(max_length=255),
        ),
    ]
