# Generated by Django 5.1.6 on 2025-02-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_exercisevideo_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_link',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
