# Generated by Django 5.1.6 on 2025-02-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_link',
            field=models.URLField(default='None', max_length=255, null=True),
        ),
    ]
