# Generated by Django 5.1.6 on 2025-02-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitCrawlerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=63, unique=True)),
                ('user_type', models.CharField(choices=[('FitKnight', 'FitKnight'), ('FitGuildOfficer', 'FitGuildOfficer')], default='FitKnight', max_length=31)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
