# Generated by Django 5.1.6 on 2025-02-07 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_fitcrawleruser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=511)),
                ('join_code', models.CharField(max_length=31, unique=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owned_gym', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fitcrawleruser',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.gym'),
        ),
    ]
