# Generated by Django 5.1.6 on 2025-02-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_gym_fitcrawleruser_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitcrawleruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
