# Generated by Django 5.1.6 on 2025-02-08 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_gymapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitcrawleruser',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.gym'),
        ),
    ]
