# Generated by Django 5.1.7 on 2025-04-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_fitcrawleruser_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitcrawleruser',
            name='profile_pic',
            field=models.CharField(default='default.png', max_length=63),
        ),
    ]
